version: "3.7"

services:
  jenkins:
    build: .
    container_name: romkitchen_master
    ports:
      - "8585:8080"
      - "50505:50000"
    volumes:
      - /var/romkitchen_master:/var/jenkins_home
