version: "3.7"

services:
  jenkins:
    build:
      args:
        gid: 1000
        group: romkitchen
      context: .
    container_name: romkitchen_master
    ports:
      - "8585:8080"
      - "50000:50000"
    volumes:
      - /var/romkitchen_master:/var/jenkins_home
